// Chapter_05/old/vue-counter.vue
<template>
    <div>
        <h1>{{count}}</h1>
        <button @click="decrement">-</button>
        <button @click="increment">+</button>
    </div>
</template>

<script>
export default {
    data() {
        return {
            count: 0,
        }
    },
    methods: {
        increment() {
            this.count += 1
        },
        decrement() {
            this.count -= 1
        }
    }
}
</script>

// Chapter_05/old/react-counter.tsx
import app from 'apprun'
import React from 'react';
import { render } from 'react-dom';
class App extends React.Component {
  state = { count: 0 }

  increment = () => {
    this.setState({
      count: this.state.count + 1
    });
  }

  decrement = () => {
    this.setState({
      count: this.state.count - 1
    });
  }

  render() {
    return <div>
      <h1>{this.state.count}</h1>
      <button onClick={this.decrement}>-</button>
      <button onClick={this.increment}>+</button>
    </div>
  }
}

render(<App />, document.getElementById('root'));
